# Generated by Django 3.2 on 2022-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_auto_20220504_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='changed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='closed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='code2fa',
            name='code',
            field=models.IntegerField(default=2677),
        ),
    ]
