# Generated by Django 3.2 on 2022-05-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_auto_20220505_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code2fa',
            name='code',
            field=models.IntegerField(default=1234),
        ),
        migrations.CreateModel(
            name='AppealPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/appeal/')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.appeal')),
            ],
        ),
    ]
